apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-web
  name: simple-web
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-web
  strategy:
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - image: hakimrizki/simple-web  
        imagePullPolicy: Always  
        name: simple-web
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi" 
      imagePullSecrets:
      - name: ocaregistry
      restartPolicy: Always
